### ISSUE TITLE
A permission to reuse code from this repo

### ISSUE THREAD

**Issue by UwUnyaa** [zphr/vim-theme-converter.el#1]
I have almost finished rewriting this script to make it work well, and I'm asking for a permission to use parts from it in my own version of it, and by that I mean mostly just contents of `face-name-list`. I can't do this without your permission, because you haven't put any license on your code.

I'd like to release my code under GNU GPL v3 if that's fine with you.

**Comment by zphr** [comment]
Wow yeah great go ahead! I am totally fine and happy that this is of use.
GPL 3 is fine!

DoMiNeLa10 <notifications@github.com> schrieb am So., 12. Feb. 2017, 21:26:

I have almost finished rewriting this script to make it work well, and I'm
asking for a permission to use parts from it in my own version of it, and
by that I mean mostly just contents of face-name-list. I can't do this
without your permission, because you haven't put any license on your code.

I'd like to release my code under GNU GPL v3 if that's fine with you.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zphr/vim-theme-converter.el/issues/1>, or mute the
thread

**Comment by UwUnyaa** [comment]
Thanks for the permission.

Here's the repo: https://github.com/DoMiNeLa10/vimco

I'll work on it to make it more user-friendly, but it's usable as of now.
